var category_ids = {
2: "Automotive",
3: "Automotive > Car Appraisers",
4: "Automotive > Car Dealers and Leasing",
5: "Automotive > Car Dealers and Leasing > Used Cars",
6: "Automotive > Car Parts and Accessories",
7: "Automotive > Car Wash and Detail",
8: "Automotive > Classic and Antique Car",
9: "Automotive > Maintenance and Repair",
10: "Automotive > Maintenance and Repair > Oil and Lube",
11: "Automotive > Maintenance and Repair > Smog Check",
12: "Automotive > Maintenance and Repair > Tires",
13: "Automotive > Maintenance and Repair > Transmissions",
14: "Automotive > Motorcycles, Mopeds and Scooters",
15: "Automotive > Motorcycles, Mopeds and Scooters > Repair",
16: "Automotive > Motorcycles, Mopeds and Scooters > Sales",
17: "Automotive > RVs and Motor Homes",
18: "Automotive > Salvage Yards",
19: "Automotive > Towing",
20: "Community and Government",
21: "Community and Government > Animal Shelters and Humane Societies",
22: "Community and Government > Cemeteries",
23: "Community and Government > Day Care and Preschools",
24: "Community and Government > Disabled Persons Services",
25: "Community and Government > Drug and Alcohol Services",
26: "Community and Government > Education",
27: "Community and Government > Education > Adult Education",
28: "Community and Government > Education > Art Lessons and Schools",
29: "Community and Government > Education > Colleges and Universities",
30: "Community and Government > Education > Computer Training",
31: "Community and Government > Education > Culinary Lessons and Schools",
32: "Community and Government > Education > Driving Schools",
33: "Community and Government > Education > Fraternities and Sororities",
34: "Community and Government > Education > Primary and Secondary Schools",
35: "Community and Government > Education > Tutoring and Educational Services",
36: "Community and Government > Education > Vocational Schools",
37: "Community and Government > Government Departments and Agencies",
453: "Community and Government > Government Departments and Agencies > Embassies",
38: "Community and Government > Government Lobbyists",
39: "Community and Government > Housing Assistance and Shelters",
40: "Community and Government > Law Enforcement and Public Safety",
42: "Community and Government > Law Enforcement and Public Safety > Fire Stations",
43: "Community and Government > Law Enforcement and Public Safety > Police Stations",
41: "Community and Government > Law Enforcement and Public Safety > Rescue Services",
44: "Community and Government > Libraries",
45: "Community and Government > Military",
46: "Community and Government > Military > Bases",
47: "Community and Government > Organizations and Associations",
48: "Community and Government > Organizations and Associations > Charities and Non-Profits",
49: "Community and Government > Organizations and Associations > Environmental",
50: "Community and Government > Organizations and Associations > Youth Organizations",
51: "Community and Government > Post Offices",
52: "Community and Government > Public and Social Services",
53: "Community and Government > Religious",
54: "Community and Government > Religious > Buddhist Temples",
55: "Community and Government > Religious > Churches",
56: "Community and Government > Religious > Hindu Temples",
57: "Community and Government > Religious > Mosques",
58: "Community and Government > Religious > Synagogues",
59: "Community and Government > Senior Citizen Services",
60: "Community and Government > Senior Citizen Services > Retirement",
61: "Community and Government > Utility Companies",
62: "Healthcare",
63: "Healthcare > AIDS Resources",
64: "Healthcare > Assisted Living Services",
65: "Healthcare > Assisted Living Services > Caretakers",
66: "Healthcare > Assisted Living Services > Facilities and Nursing Homes",
67: "Healthcare > Blood Banks and Centers",
68: "Healthcare > Chiropractors",
69: "Healthcare > Dentists",
70: "Healthcare > Emergency Services",
71: "Healthcare > Emergency Services > Ambulance",
72: "Healthcare > Holistic, Alternative and Naturopathic Medicine",
73: "Healthcare > Holistic, Alternative and Naturopathic Medicine > Acupuncture",
74: "Healthcare > Hospitals, Clinics and Medical Centers",
75: "Healthcare > Medical Supplies and Labs",
76: "Healthcare > Mental Health",
77: "Healthcare > Mental Health > Counseling and Therapy",
78: "Healthcare > Mental Health > Psychologists",
79: "Healthcare > Nurses",
80: "Healthcare > Pharmacies",
81: "Healthcare > Physical Therapy and Rehabilitation",
82: "Healthcare > Physical Therapy and Rehabilitation > Sports Medicine",
83: "Healthcare > Physicians",
84: "Healthcare > Physicians > Anesthesiologists",
85: "Healthcare > Physicians > Cardiologists",
86: "Healthcare > Physicians > Dermatologists",
87: "Healthcare > Physicians > Ear, Nose and Throat",
88: "Healthcare > Physicians > Family Medicine",
89: "Healthcare > Physicians > Gastroenterologists",
90: "Healthcare > Physicians > General Surgery",
441: "Healthcare > Physicians > Geriatrics",
91: "Healthcare > Physicians > Internal Medicine",
92: "Healthcare > Physicians > Neurologists",
93: "Healthcare > Physicians > Obstetricians and Gynecologists",
94: "Healthcare > Physicians > Oncologists",
95: "Healthcare > Physicians > Ophthalmologists",
96: "Healthcare > Physicians > Orthopedic Surgeons",
97: "Healthcare > Physicians > Pathologists",
98: "Healthcare > Physicians > Pediatricians",
99: "Healthcare > Physicians > Plastic Surgeons",
100: "Healthcare > Physicians > Psychiatrists",
101: "Healthcare > Physicians > Radiologists",
102: "Healthcare > Physicians > Respiratory",
103: "Healthcare > Physicians > Urologists",
104: "Healthcare > Podiatrists",
105: "Healthcare > Pregnancy and Sexual Health",
106: "Healthcare > Weight Loss and Nutritionists",
107: "Landmarks",
108: "Landmarks > Buildings and Structures",
109: "Landmarks > Gardens",
110: "Landmarks > Historic and Protected Sites",
111: "Landmarks > Monuments and Memorials",
112: "Landmarks > Natural",
113: "Landmarks > Natural > Beaches",
115: "Landmarks > Natural > Forests",
116: "Landmarks > Natural > Lakes",
114: "Landmarks > Natural > Mountains",
117: "Landmarks > Natural > Rivers",
118: "Landmarks > Parks",
119: "Landmarks > Parks > Natural Parks",
120: "Landmarks > Parks > Picnic Areas",
121: "Landmarks > Parks > Playgrounds",
122: "Landmarks > Parks > Urban Parks",
123: "Retail",
124: "Retail > Adult",
125: "Retail > Antiques",
126: "Retail > Arts and Crafts",
127: "Retail > Auctions",
128: "Retail > Beauty Products",
129: "Retail > Bicycles",
130: "Retail > Bookstores",
131: "Retail > Cards and Stationery",
132: "Retail > Children",
133: "Retail > Computers and Electronics",
134: "Retail > Computers and Electronics > Cameras",
135: "Retail > Computers and Electronics > Mobile Phones",
136: "Retail > Computers and Electronics > Video Games",
137: "Retail > Construction Supplies",
138: "Retail > Convenience Stores",
139: "Retail > Costumes",
140: "Retail > Dance and Music",
141: "Retail > Department Stores",
442: "Retail > Discount Stores",
142: "Retail > Fashion",
143: "Retail > Fashion > Clothing and Accessories",
144: "Retail > Fashion > Jewelry and Watches",
145: "Retail > Fashion > Shoes",
146: "Retail > Fashion > Swimwear",
147: "Retail > Flea Markets",
148: "Retail > Florists",
149: "Retail > Food and Beverage",
150: "Retail > Food and Beverage > Beer, Wine and Spirits",
151: "Retail > Food and Beverage > Candy Stores",
152: "Retail > Food and Beverage > Cheese",
153: "Retail > Food and Beverage > Chocolate",
154: "Retail > Food and Beverage > Farmers’ Markets",
155: "Retail > Food and Beverage > Health and Diet Food",
156: "Retail > Food and Beverage > Kosher",
443: "Retail > Food and Beverage > Meat and Seafood",
157: "Retail > Furniture and Decor",
158: "Retail > Gift and Novelty",
159: "Retail > Glasses and Optometrist",
160: "Retail > Hobby and Collectibles",
248: "Retail > Home Appliances",
250: "Retail > Housewares",
161: "Retail > Luggage",
162: "Retail > Music, Video and DVD",
163: "Retail > Newsstands",
164: "Retail > Nurseries and Garden Centers",
444: "Retail > Office Supplies",
165: "Retail > Outlet",
445: "Retail > Party Supplies",
166: "Retail > Pawn Shops",
167: "Retail > Pets",
168: "Retail > Photos and Frames",
169: "Retail > Shopping Centers and Malls",
170: "Retail > Sporting Goods",
171: "Retail > Supermarkets and Groceries",
172: "Retail > Tobacco",
173: "Retail > Toys",
174: "Retail > Vintage and Thrift",
175: "Retail > Warehouses and Wholesale Stores",
176: "Retail > Wedding and Bridal",
177: "Businesses and Services",
193: "Businesses and Services > Advertising and Marketing",
194: "Businesses and Services > Advertising and Marketing > Advertising Agencies and Media Buyers",
195: "Businesses and Services > Advertising and Marketing > Creative Services",
196: "Businesses and Services > Advertising and Marketing > Direct Mail and Email Marketing Services",
197: "Businesses and Services > Advertising and Marketing > Market Research and Consulting",
198: "Businesses and Services > Advertising and Marketing > Online Advertising",
199: "Businesses and Services > Advertising and Marketing > Print, TV, Radio and Outdoor Advertising",
200: "Businesses and Services > Advertising and Marketing > Promotional Items",
201: "Businesses and Services > Advertising and Marketing > Public Relations",
202: "Businesses and Services > Advertising and Marketing > Search Engine Marketing and Optimization",
203: "Businesses and Services > Advertising and Marketing > Writing, Copywriting and Technical Writing",
204: "Businesses and Services > Agriculture and Forestry",
205: "Businesses and Services > Art Restoration",
206: "Businesses and Services > Audiovisual",
207: "Businesses and Services > Automation and Control Systems",
178: "Businesses and Services > Business and Strategy Consulting",
446: "Businesses and Services > Career Counseling",
208: "Businesses and Services > Chemicals and Gasses",
209: "Businesses and Services > Computers",
447: "Businesses and Services > Construction",
210: "Businesses and Services > Corporate HQ",
211: "Businesses and Services > Electrical Equipment",
212: "Businesses and Services > Employment Agencies",
213: "Businesses and Services > Engineering",
214: "Businesses and Services > Entertainment",
215: "Businesses and Services > Entertainment > Media",
216: "Businesses and Services > Equipment Rental",
217: "Businesses and Services > Events and Event Planning",
219: "Businesses and Services > Financial",
220: "Businesses and Services > Financial > Accounting and Bookkeeping",
221: "Businesses and Services > Financial > Banking and Finance",
218: "Businesses and Services > Financial > Banking and Finance > ATMs",
222: "Businesses and Services > Financial > Business Brokers and Franchises",
223: "Businesses and Services > Financial > Check Cashing",
224: "Businesses and Services > Financial > Collections",
225: "Businesses and Services > Financial > Financial Planning and Investments",
226: "Businesses and Services > Financial > Fund Raising",
227: "Businesses and Services > Financial > Loans and Mortgages",
228: "Businesses and Services > Financial > Stock Brokers",
229: "Businesses and Services > Financial > Student Aid and Grants",
230: "Businesses and Services > Food and Beverage",
231: "Businesses and Services > Food and Beverage > Catering",
232: "Businesses and Services > Food and Beverage > Distribution",
233: "Businesses and Services > Funeral Services",
234: "Businesses and Services > Geological",
235: "Businesses and Services > Home Improvement",
236: "Businesses and Services > Home Improvement > Architects",
237: "Businesses and Services > Home Improvement > Carpenters",
238: "Businesses and Services > Home Improvement > Carpet and Flooring",
239: "Businesses and Services > Home Improvement > Contractors",
240: "Businesses and Services > Home Improvement > Contractors > Bathrooms",
241: "Businesses and Services > Home Improvement > Contractors > Deck and Patio",
242: "Businesses and Services > Home Improvement > Contractors > Sewer",
243: "Businesses and Services > Home Improvement > Doors and Windows",
244: "Businesses and Services > Home Improvement > Electricians",
245: "Businesses and Services > Home Improvement > Fences, Fireplaces and Garage Doors",
246: "Businesses and Services > Home Improvement > Hardware and Services",
247: "Businesses and Services > Home Improvement > Heating, Ventilating and Air Conditioning",
249: "Businesses and Services > Home Improvement > Home Inspection Services",
251: "Businesses and Services > Home Improvement > Interior Design",
252: "Businesses and Services > Home Improvement > Kitchens",
253: "Businesses and Services > Home Improvement > Landscaping and Gardeners",
254: "Businesses and Services > Home Improvement > Lighting Fixtures",
256: "Businesses and Services > Home Improvement > Movers",
257: "Businesses and Services > Home Improvement > Painting",
258: "Businesses and Services > Home Improvement > Pest Control",
259: "Businesses and Services > Home Improvement > Plumbing",
260: "Businesses and Services > Home Improvement > Pools and Spas",
261: "Businesses and Services > Home Improvement > Roofers",
263: "Businesses and Services > Home Improvement > Swimming Pool Maintenance and Services",
264: "Businesses and Services > Home Improvement > Tree Service",
265: "Businesses and Services > Home Improvement > Upholstery",
266: "Businesses and Services > Human Resources",
267: "Businesses and Services > Import and Export",
179: "Businesses and Services > Industrial Machinery and Vehicles",
272: "Businesses and Services > Insurance",
268: "Businesses and Services > Leather",
269: "Businesses and Services > Legal",
270: "Businesses and Services > Legal > Credit Counseling and Bankruptcy Services",
271: "Businesses and Services > Legal > Immigration",
448: "Businesses and Services > Legal > Notary",
180: "Businesses and Services > Logging and Sawmills",
273: "Businesses and Services > Machine Shops",
274: "Businesses and Services > Management",
275: "Businesses and Services > Manufacturing",
181: "Businesses and Services > Metals",
182: "Businesses and Services > Packaging",
276: "Businesses and Services > Paper",
277: "Businesses and Services > Personal Care",
280: "Businesses and Services > Personal Care > Beauty Salons and Barbers",
278: "Businesses and Services > Personal Care > Dry Cleaning, Ironing and Laundry",
279: "Businesses and Services > Personal Care > Hair Removal",
281: "Businesses and Services > Personal Care > Manicures and Pedicures",
282: "Businesses and Services > Personal Care > Massage Clinics and Therapists",
283: "Businesses and Services > Personal Care > Piercing",
284: "Businesses and Services > Personal Care > Skin Care",
285: "Businesses and Services > Personal Care > Spas",
286: "Businesses and Services > Personal Care > Tanning Salons",
287: "Businesses and Services > Personal Care > Tattooing",
183: "Businesses and Services > Petroleum",
449: "Businesses and Services > Photography",
184: "Businesses and Services > Plastics",
288: "Businesses and Services > Printing, Copying and Signage",
289: "Businesses and Services > Professional Cleaning",
290: "Businesses and Services > Publishing",
291: "Businesses and Services > Real Estate",
296: "Businesses and Services > Real Estate > Apartments, Condos, and Houses",
297: "Businesses and Services > Real Estate > Boarding Houses",
298: "Businesses and Services > Real Estate > Building and Land Surveyors",
299: "Businesses and Services > Real Estate > Commercial Real Estate",
300: "Businesses and Services > Real Estate > Corporate Housing",
255: "Businesses and Services > Real Estate > Mobile Homes",
292: "Businesses and Services > Real Estate > Property Management",
293: "Businesses and Services > Real Estate > Real Estate Agents",
294: "Businesses and Services > Real Estate > Real Estate Appraiser",
295: "Businesses and Services > Real Estate > Real Estate Development and Title Companies",
185: "Businesses and Services > Refrigeration and Ice",
301: "Businesses and Services > Renewable Energy",
302: "Businesses and Services > Repair Services",
186: "Businesses and Services > Rubber",
187: "Businesses and Services > Scientific",
188: "Businesses and Services > Security and Safety",
303: "Businesses and Services > Shipping, Freight, and Material Transportation",
262: "Businesses and Services > Storage",
304: "Businesses and Services > Tailors",
460: "Businesses and Services > Technology",
456: "Businesses and Services > Technology > Advertising",
454: "Businesses and Services > Technology > Infrastructure",
455: "Businesses and Services > Technology > Mobile",
306: "Businesses and Services > Technology > Web Design and Development",
189: "Businesses and Services > Telecommunication Services",
190: "Businesses and Services > Textiles",
450: "Businesses and Services > Translation Services",
305: "Businesses and Services > Veterinarians",
191: "Businesses and Services > Water and Waste Management",
192: "Businesses and Services > Welding",
307: "Businesses and Services > Wholesale",
308: "Social",
309: "Social > Arts",
310: "Social > Arts > Art Dealers and Galleries",
311: "Social > Arts > Museums",
312: "Social > Bars",
313: "Social > Bars > Hotel Lounges",
314: "Social > Bars > Jazz and Blues Cafes",
315: "Social > Bars > Sports Bars",
316: "Social > Bars > Wine Bars",
317: "Social > Entertainment",
318: "Social > Entertainment > Adult",
319: "Social > Entertainment > Arcades and Amusement Parks",
320: "Social > Entertainment > Billiard and Pool",
321: "Social > Entertainment > Bingo",
322: "Social > Entertainment > Bowling",
323: "Social > Entertainment > Carnivals",
324: "Social > Entertainment > Casinos and Gaming",
325: "Social > Entertainment > Circuses",
326: "Social > Entertainment > Dance Halls and Saloons",
327: "Social > Entertainment > Fairgrounds and Rodeos",
328: "Social > Entertainment > Go Carts",
329: "Social > Entertainment > Hookah Lounges",
330: "Social > Entertainment > Karaoke",
331: "Social > Entertainment > Miniature Golf",
332: "Social > Entertainment > Movie Theatres",
333: "Social > Entertainment > Music and Show Venues",
334: "Social > Entertainment > Night Clubs",
335: "Social > Entertainment > Party Centers",
336: "Social > Entertainment > Psychics and Astrologers",
337: "Social > Entertainment > Ticket Sales",
338: "Social > Food and Dining",
339: "Social > Food and Dining > Bagels and Donuts",
340: "Social > Food and Dining > Bakeries",
341: "Social > Food and Dining > Breweries",
342: "Social > Food and Dining > Cafes, Coffee and Tea Houses",
343: "Social > Food and Dining > Dessert",
344: "Social > Food and Dining > Ice Cream Parlors",
345: "Social > Food and Dining > Internet Cafes",
346: "Social > Food and Dining > Juice Bars and Smoothies",
347: "Social > Food and Dining > Restaurants",
348: "Social > Food and Dining > Restaurants > American",
457: "Social > Food and Dining > Restaurants > Asian",
349: "Social > Food and Dining > Restaurants > Barbecue",
350: "Social > Food and Dining > Restaurants > Buffets",
351: "Social > Food and Dining > Restaurants > Burgers",
352: "Social > Food and Dining > Restaurants > Chinese",
353: "Social > Food and Dining > Restaurants > Delis",
354: "Social > Food and Dining > Restaurants > Diners",
355: "Social > Food and Dining > Restaurants > Fast Food",
458: "Social > Food and Dining > Restaurants > Food Trucks",
356: "Social > Food and Dining > Restaurants > French",
357: "Social > Food and Dining > Restaurants > Indian",
358: "Social > Food and Dining > Restaurants > Italian",
359: "Social > Food and Dining > Restaurants > Japanese",
360: "Social > Food and Dining > Restaurants > Korean",
361: "Social > Food and Dining > Restaurants > Mexican",
362: "Social > Food and Dining > Restaurants > Middle Eastern",
363: "Social > Food and Dining > Restaurants > Pizza",
364: "Social > Food and Dining > Restaurants > Seafood",
365: "Social > Food and Dining > Restaurants > Steakhouses",
366: "Social > Food and Dining > Restaurants > Sushi",
367: "Social > Food and Dining > Restaurants > Thai",
368: "Social > Food and Dining > Restaurants > Vegan and Vegetarian",
369: "Social > Social Clubs",
370: "Social > Wineries and Vineyards",
371: "Social > Zoos, Aquariums and Wildlife Sanctuaries",
372: "Sports and Recreation",
373: "Sports and Recreation > Athletic Fields",
374: "Sports and Recreation > Baseball",
375: "Sports and Recreation > Baseball > Batting Ranges",
376: "Sports and Recreation > Basketball",
377: "Sports and Recreation > Combat Sports",
378: "Sports and Recreation > Cycling",
379: "Sports and Recreation > Dance",
380: "Sports and Recreation > Equestrian",
381: "Sports and Recreation > Football",
382: "Sports and Recreation > Golf",
451: "Sports and Recreation > Golf > Golf Courses",
383: "Sports and Recreation > Gun Ranges",
384: "Sports and Recreation > Gymnastics",
385: "Sports and Recreation > Gyms and Fitness Centers",
386: "Sports and Recreation > Hockey",
387: "Sports and Recreation > Outdoors",
388: "Sports and Recreation > Outdoors > Campgrounds and RV Parks",
389: "Sports and Recreation > Outdoors > Hiking",
390: "Sports and Recreation > Outdoors > Hot Air Balloons",
391: "Sports and Recreation > Outdoors > Hunting and Fishing",
392: "Sports and Recreation > Outdoors > Rock Climbing",
393: "Sports and Recreation > Outdoors > Skydiving",
394: "Sports and Recreation > Paintball",
395: "Sports and Recreation > Personal Trainers",
396: "Sports and Recreation > Race Tracks",
397: "Sports and Recreation > Racquet Sports",
398: "Sports and Recreation > Racquet Sports > Racquetball",
399: "Sports and Recreation > Racquet Sports > Tennis",
400: "Sports and Recreation > Recreation Centers",
401: "Sports and Recreation > Running",
402: "Sports and Recreation > Skating",
403: "Sports and Recreation > Snow Sports",
404: "Sports and Recreation > Soccer",
405: "Sports and Recreation > Sports Clubs",
406: "Sports and Recreation > Stadiums and Arenas",
407: "Sports and Recreation > Swimming Pools",
408: "Sports and Recreation > Water Sports",
409: "Sports and Recreation > Water Sports > Boating",
410: "Sports and Recreation > Water Sports > Canoes and Kayaks",
411: "Sports and Recreation > Water Sports > Rafting",
412: "Sports and Recreation > Water Sports > Scuba Diving",
452: "Sports and Recreation > Water Sports > Surfing",
413: "Sports and Recreation > Water Sports > Swimming",
414: "Sports and Recreation > Yoga and Pilates",
415: "Transportation",
416: "Transportation > Airlines and Aviation Services",
417: "Transportation > Gas Stations",
418: "Transportation > Parking",
419: "Transportation > Public Transportation Services",
459: "Transportation > Rest Areas",
420: "Transportation > Taxi and Car Services",
421: "Transportation > Taxi and Car Services > Car and Truck Rentals",
422: "Transportation > Taxi and Car Services > Charter Buses",
423: "Transportation > Taxi and Car Services > Limos and Chauffeurs",
424: "Transportation > Transport Hubs",
425: "Transportation > Transport Hubs > Airports",
426: "Transportation > Transport Hubs > Bus Stations",
427: "Transportation > Transport Hubs > Heliports",
428: "Transportation > Transport Hubs > Ports",
429: "Transportation > Transport Hubs > Rail Stations",
430: "Travel",
431: "Travel > Cruises",
432: "Travel > Lodging",
433: "Travel > Lodging > Bed and Breakfasts",
434: "Travel > Lodging > Cottages and Cabins",
435: "Travel > Lodging > Hostels",
436: "Travel > Lodging > Hotels and Motels",
437: "Travel > Lodging > Lodges and Vacation Rentals",
438: "Travel > Lodging > Resorts",
439: "Travel > Tourist Information and Services",
440: "Travel > Travel Agents and Tour Operators"}